[server]
port=8080

[redis]
enable=false
prefix="qs"
host=""
password=""
port=6379
maxIdle=3
maxActive=10

[log]
level="debug"
showCode=true
dir="logs"
rotate=10

[database]
driver="mysql"
host=""
user=""
password=""
db=""
port=3306
prefix=""
showSql=true